version: 2.1

jobs:
  maven_test:
    docker:
      - image: 'cimg/openjdk:11.0@sha256:b50bf132993960b2e515a2baa273297945d3725893c6e345f5fd95a253e5b841'
    steps:
      - checkout
      - run:
          name: Generate Cache Checksum
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
      - restore_cache:
          name: Restoring cache
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          name: Install Dependencies
          command: ./scripts/install_dependencies.sh && mvn dependency:go-offline
      - run:
          name: Run Tests
          command: mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dmaven.javadoc.skip=true -Dgpg.skip=true
      - save_cache:
          paths:
            - ~/.m2/repository
          key: maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: target/surefire-reports

workflows:
  maven_test:
    jobs:
      - maven_test


# Uncomment when idl-choco and idlreasoner-choco are uploaded to mvnrepository

#version: 2.1
#
#orbs:
#  maven: circleci/maven@1.0.3
#
#workflows:
#  maven_test:
#    jobs:
#      - maven/test:
#          command: verify  org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dmaven.javadoc.skip=true -Dgpg.skip=true
